global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'discovery-service:8201' ]
        labels:
          service: 'discovery'
          environment: 'dev'

  - job_name: 'authentication-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['authentication-service:8197']
        labels:
          service: 'authentication'
          environment: 'dev'

  - job_name: 'restaurant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['restaurant-service:8198']
        labels:
          service: 'restaurant'
          environment: 'dev'

  - job_name: 'booking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['booking-service:8199']
        labels:
          service: 'booking'
          environment: 'dev'

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:8200' ]
        labels:
          service: 'gateway'
          environment: 'dev'