spring.application.name=discovery_service
server.port=8201

eureka.client.service-url.defaultZone=http://localhost:8201/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
eureka.instance.hostname=localhost

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always