spring.application.name=authenticationService

server.servlet.path=/
server.port=8197

#jwt
jwt.secret=ZMTqj2ohFF6ZkXdBFd9Q4eW4JFqYCcDQo67LclJTBfZJGDpUOueXGxWiAzjyJ39a3dQwEW706NBnW8ud11wVlw==
jwt.lifetime=3600000
jwt.expiration=103600000

#sql
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=foodie_authentication
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=foodie_authentication

#swagger
swagger.servers.first=http://localhost:8197
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#endpoints authentication
end.point.authentication=/authentication
end.point.user.register=/user/register
end.point.user.login=/user/login
end.point.owner.register=/owner/register
end.point.owner.login=/owner/login
end.point.validate=/validate
end.point.refresh.token=/refresh

#endpoints other
end.point.owner=/owner
end.point.user=/user
end.point.id=/{id}



