spring.application.name=api_gateway

server.port=8888

# Swagger настройки
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springdoc=DEBUG