spring.application.name=restaurant_service

server.servlet.context-path=/
server.port=8198

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=foodie_restaurants
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=foodie_restaurants

#swagger
swagger.servers.first=http://localhost:8198
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#end points
end.point.restaurant=/restaurant
end.point.id=/{id}
end.point.add=/add
end.point.search=/search

end.point.restaurant.id.tables=/restaurant/{id}/tables
end.point.tableId=/{numberOfTable}

auth.service.url=http://localhost:8197