spring.application.name=restaurant_service

server.servlet.context-path=/
server.port=8198

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=foodie_restaurants
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=foodie_restaurants

#end poins
end.point.restaurant=/restaurant
end.point.id=/{id}
end.point.add=/add
end.point.search=/search

auth.service.url=http://localhost:8197